---
title: "Milano Air Quality Dashboard"
execute:
  echo: false
format:
  html: 
    theme:
      - default
      - style/custom.scss
    page-layout: custom
    margin-left: 10px
    margin-top: 10px
    margin-right: 10px
    margin-bottom: 10px
editor_options: 
  chunk_output_type: console
---

```{r notes}
#| include: false

# https://www.eea.europa.eu/themes/air/air-quality-concentrations/AirQlimitvalues.png
# https://environment.ec.europa.eu/topics/air/air-quality/eu-air-quality-standards_en
# https://dati.comune.milano.it/dataset/ds411-rilevazione-qualita-aria-2022
```


```{r packages}
#| include: false
library(tidyverse)
library(here)
library(tsibble)
library(lubridate)
library(ggiraph)
library(glue)
```

```{r functions}
#| include: false
source(
  here('R/utils.R')
)
```


```{r params}
#| include: false

label_size <- 9
thin_line <- .2
medium_line <- 1
anno_size <- 2
bkg_colour <- 'white'
limits_colour <- 'red'
def_colour <- 'blue'
mid_colour <- 'grey50'
mid_light <- 'grey80'
hover_colour <- '#FF00FF'
loess_span <- .2 # span should increase during the year
ozone_limits <- 120
height_svg <- 2.2
pointsize <- 10
```


```{r params-ggplot}
#| include: false
theme_set(
  theme_minimal() +
    theme(
      axis.text.x = element_text(
        angle = 90,
        vjust = 0,
        hjust = 1,
        size = label_size
      ),
      axis.text.y = element_text(
        vjust = 0,
        hjust = 1,
        size = label_size
      ),
      axis.title.y = element_text(
        hjust = 1,
        vjust = 2,
        size = label_size
      )
    ) 
)
```


```{r params-ggiraph}
#| include: false

set_girafe_defaults(
  opts_tooltip = opts_tooltip(
    opacity = 1,
    css = glue("background-color:#333333;",
               "color:white;padding:3px;",
               "border-radius:2px;")
  ),
  opts_sizing = opts_sizing(
    rescale = TRUE,
    width = 1
  )
)
```


```{r params-pollutants}
#| include: false

# from https://environment.ec.europa.eu/topics/air/air-quality/eu-air-quality-standards_en
pollutants <- 
  tribble(~inquinante, ~pollutant_name, ~eu_limits,
          'C6H6', 'Polycyclic Aromatic Hydrocarbons', 1e-3,
          'CO_8h', 'Carbon Monoxide', 1e4,
          'NO2', 'Nitrogen Dioxide', 40,
          'O3', 'Ozone', 120,
          'PM10', 'Particulate Matter', 40,
          'PM25', 'Fine Particles', 20,
          'SO2', 'Sulphur Dioxide', 125,
          )
```

```{r data-wrangling}
#| include: false

air_q_url <-
  'data/e1cc82ec-97bb-463c-a3fb-b61be60f0956.csv'

air_q <- 
  air_q_url %>% 
  readr::read_csv() %>% 
  janitor::clean_names() %>% 
  rename(date = data) %>% 
  mutate(date = date %>% as_date()) %>% 
  # guessing real order of magnitude of measuremnts
  mutate(valore = valore %>% {
    case_when(inquinante == 'C6H6' ~ . * 1e-3,
              inquinante == 'CO_8h' ~ . * 1e3,
              TRUE ~ .)
  }) %>% 
  group_by(inquinante) %>% 
  nest() %>% 
  left_join(pollutants)

# For scatterplots -------------------------------------
air_q$plots <- air_q %>% pmap(plot_pollutant)


# For heatmap ------------------------------------------
air_q$data_scaled <- 
  air_q %>% 
  pmap(scale_pollutant)

air_q_scaled <-
  air_q %>% 
  select(inquinante, pollutant_name, data_scaled) %>% 
  unnest(data_scaled)
```

:::::: {.grid}

::::: {.g-col-8}

::: {.g-col-12}

```{r heatmap}
#| panel: fill
plot_heat(air_q_scaled)
```

:::

:::: {.g-col-12}

::: {.panel-tabset}

### Ozone

```{r ozone}
#| panel: fill
air_q %>% filter(pollutant_name == 'Ozone') %>% pull(plots) %>% .[[1]]
```

### Nitrogen Dioxide

```{r no}
#| panel: fill
air_q %>% filter(pollutant_name == 'Nitrogen dioxide') %>% pull(plots) %>% .[[1]]
```

### Polycyclic Aromatics

```{r aro}
#| panel: fill
air_q %>% filter(pollutant_name == 'Polycyclic Aromatic Hydrocarbons') %>% pull(plots) %>% .[[1]]
```

### PM10

```{r pm10}
#| panel: fill
air_q %>% filter(pollutant_name == 'Particulate matter') %>% pull(plots) %>% .[[1]]
```

### PM2.5

```{r pm25}
#| panel: fill
air_q %>% filter(pollutant_name == 'Fine particles') %>% pull(plots) %>% .[[1]]
```

### Sulphur Dioxide

```{r so}
#| panel: fill
air_q %>% filter(pollutant_name == 'Sulphur dioxide') %>% pull(plots) %>% .[[1]]
```

### Carbon Monoxide

```{r co}
#| panel: fill
air_q %>% filter(pollutant_name == 'Carbon monoxide') %>% pull(plots) %>% .[[1]]
```

:::

::::

:::::

::::: {.g-col-4}

### Some stats

and info

:::::

:::::