---
title: "Milano Air Quality Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    # vertical_layout: scroll
editor_options: 
  chunk_output_type: console
---

```{r notes, include=FALSE}
# https://www.eea.europa.eu/themes/air/air-quality-concentrations/AirQlimitvalues.png
  # https://environment.ec.europa.eu/topics/air/air-quality/eu-air-quality-standards_en
# https://dati.comune.milano.it/dataset/ds411-rilevazione-qualita-aria-2022
```


```{r packages, include=FALSE}
library(tidyverse)
library(here)
library(tsibble)
library(lubridate)
library(ggiraph)
```

```{r params, include=FALSE}
label_size <- 9
thin_line <- .2
medium_line <- .5
limits_colour <- 'red'
def_colour <- 'blue'
mid_colour <- 'grey50'
loess_span <- .2 # span should increase during the year
ozone_limits <- 120
height_svg <- 3
pointsize <- 10

theme_set(
  theme_minimal() +
    theme(
      axis.text.x = element_text(
        angle = 90,
        vjust = 0,
        hjust = 1,
        size = label_size
      ),
      axis.text.y = element_text(
        vjust = 0,
        hjust = 1,
        size = label_size
      ),
      axis.title.y = element_text(
        hjust = 1,
        vjust = 2,
        size = label_size
      )
    ) 
)

# from https://environment.ec.europa.eu/topics/air/air-quality/eu-air-quality-standards_en
pollutants <- 
  tribble(~inquinante, ~pollutant_name, ~eu_limits,
          'C6H6', 'Polycyclic Aromatic Hydrocarbons', 1e-3,
          'CO_8h', 'Carbon monoxide', 1e4,
          'NO2', 'Nitrogen dioxide', 40,
          'O3', 'Ozone', 120,
          'PM10', 'Particulate matter', 40,
          'PM25', 'Fine particles', 20,
          'SO2', 'Sulphur dioxide', 125,
          )
```

```{r functions}
scale_pollutant <- 
  function(data, eu_limits, ...) {

    data <-
      data %>% 
      group_by(date) %>% 
      summarise(
        across(
          .cols = valore,
          .fns = ~median(., na.rm = T)
        )
      ) %>% 
      mutate(scaled = valore/eu_limits) %>% 
      ungroup() %>% 
      as_tsibble(index = 'date') %>% 
      fill_gaps() %>% 
      fill(valore, scaled, .direction = 'down') %>% 
      as_tibble()
    
    return(data)
  }

breaks_on_fortnight <- function(x) {
  n_days <- 14
  d <- seq.Date(from = min(x),
                to = max(x) + days(n_days - 1),
                by = n_days)
  return(d - days(n_days - 1))
}

plot_pollutant <- function(data,
                           eu_limits,
                           pollutant_name,
                           ...) {
  
  p <- 
    data %>%  
    ggplot(
      aes(
        x = date,
        y = valore,
      )
    ) +
    geom_hline(yintercept = 0) +
    geom_hline(yintercept = eu_limits,
               colour = mid_colour,
               size = thin_line, 
               lty = '1212')  +
    geom_smooth(size = medium_line,
                colour = '#00000000',
                method = 'loess',
                span = loess_span) +
    geom_point_interactive(
      aes(tooltip = glue::glue('Data: {date}\nValore: {valore}'),
          colour = after_stat(y)),
      size = 1,
      alpha = .8) +
    scale_colour_gradient2_interactive(
      low = def_colour,
      mid = mid_colour,
      high = limits_colour,
      midpoint = eu_limits
    ) +
    scale_x_date(
      breaks = breaks_on_fortnight,
      minor_breaks = NULL,
      expand = expansion(mult = c(.01, .1)),
      date_labels = '%b %d'
    ) +
    guides(colour = 'none') +
    labs(x = '',
         y = 'Concentration [µg/m3]',
         title = pollutant_name)
  
  g <- 
    girafe(
    ggobj = p,
    height_svg = height_svg,
    pointsize = pointsize,
    options = list(
      opts_sizing(rescale = TRUE, width = 1)
    ))
  
  return(g)
}
```

```{r data, include=FALSE}  
air_q_url <-
  'data/e1cc82ec-97bb-463c-a3fb-b61be60f0956.csv'

air_q <- 
  air_q_url %>% 
  readr::read_csv() %>% 
  janitor::clean_names() %>% 
  rename(date = data) %>% 
  mutate(date = date %>% as_date()) %>% 
  # guessing real order of magnitude of measuremnts
  mutate(valore = valore %>% {
    case_when(inquinante == 'C6H6' ~ . * 1e-3,
              inquinante == 'CO_8h' ~ . * 1e3,
              TRUE ~ .)
  }) %>% 
  group_by(inquinante) %>% 
  nest() %>% 
  left_join(pollutants)

```


```{r viz, include=FALSE}
air_q$plots <- air_q %>% pmap(plot_pollutant)
```

Column {data-width=700}
------------------------------------
Row
-------------------------------------

### All Pollutants  {data-height=300}

```{r heatmap}
air_q$data_scaled <- 
  air_q %>% 
  pmap(scale_pollutant)

air_q_scaled <-
  air_q %>% 
  select(inquinante, pollutant_name, data_scaled) %>% 
  unnest(data_scaled)

p_heat <- 
  air_q_scaled %>% 
  ggplot() +
  aes(
    x = date,
    y = inquinante, 
    fill = scaled,
    colour = after_stat(fill)
  ) +
  geom_tile_interactive(
    aes(tooltip = glue::glue('Data: {date}
                              Pollutant: {inquinante}
                             Valore: {scaled}')), 
    size = 0
    # hover_css = 'stroke-colour:0c0c02;'
  ) +
  scale_fill_gradient2(
      low = def_colour,
      mid = mid_colour,
      high = limits_colour,
      midpoint = 1,
      limits = c(0, NA)
    ) +
  scale_colour_gradient2(
      low = def_colour,
      mid = mid_colour,
      high = limits_colour,
      midpoint = 1
    ) +
  scale_x_date(
    breaks = breaks_on_fortnight,
    minor_breaks = NULL,
    expand = expansion(mult = c(.01, .1)),
    date_labels = '%b %d'
  ) +
  guides(fill = 'none',
         colour = 'none') +
  labs(x = '',
       y = 'Concentration [µg/m3]') +
  theme(panel.grid = element_blank())


girafe(
  ggobj = p_heat,
  height_svg = height_svg,
  pointsize = pointsize,
  options = list(
    opts_sizing(rescale = TRUE, width = 1)
  ))
```


Row {.tabset .tabset-fade}
-------------------------------------

### Ozone

```{r ozone}
air_q %>% filter(pollutant_name == 'Ozone') %>% pull(plots) %>% .[[1]]
```

### Nitrogen dioxide

```{r no}
air_q %>% filter(pollutant_name == 'Nitrogen dioxide') %>% pull(plots) %>% .[[1]]
```

### Polycyclic Aromatics

```{r aro}
air_q %>% filter(pollutant_name == 'Polycyclic Aromatic Hydrocarbons') %>% pull(plots) %>% .[[1]]
```

### Particulate matter PM10

```{r pm10}
air_q %>% filter(pollutant_name == 'Particulate matter') %>% pull(plots) %>% .[[1]]
```

### Fine particles PM2.5

```{r pm25}
air_q %>% filter(pollutant_name == 'Fine particles') %>% pull(plots) %>% .[[1]]
```

### Sulphur dioxide

```{r so}
air_q %>% filter(pollutant_name == 'Sulphur dioxide') %>% pull(plots) %>% .[[1]]
```

### Carbon monoxide

```{r co}
air_q %>% filter(pollutant_name == 'Carbon monoxide') %>% pull(plots) %>% .[[1]]
```

Column {data-width=300}
-------------------------------------------
